/*
-- Query: SELECT * FROM events.event
LIMIT 0, 1000

-- Date: 2023-11-10 18:24
*/
INSERT INTO `` (`id`,`title`,`description`,`image`,`date`,`author`,`text`,`location`) VALUES (1,'Alpha-Con','Convención de Anime, Videojuegos y más','https://th.bing.com/th/id/R.f92e78b4388109805d75731553a2acaf?rik=hk2n4oX6jycSjw&pid=ImgRaw&r=0','2023-12-07','Aurelio Flores','La Alpha-Con se celebra hace años, reuniendo a otakus, frikis y un sin fin más de personas apasionadas por el mundo geek','San Luis Río Colorado');
INSERT INTO `` (`id`,`title`,`description`,`image`,`date`,`author`,`text`,`location`) VALUES (2,'Vive San Luis','Evento cultural de música, conviencia y promoción de empresas','https://th.bing.com/th/id/R.cc4994c2f778931814f845301421070f?rik=Yu5jGUjNiiz19Q&pid=ImgRaw&r=0','2023-11-16','Gobierno de San Luis Río Colorado','Vive San Luis es un evento en el cual los ciudadanos del pueblo se reunen para celebrar, pasar un buen rato y escuchar buena música. Se suele celebrar en el parque Benito Juárez','San Lis Río Colorado');
INSERT INTO `` (`id`,`title`,`description`,`image`,`date`,`author`,`text`,`location`) VALUES (11,'Feria del Algodon','Una feria que se celebra cada año con motivo de fin de año','https://th.bing.com/th/id/R.f1dbc2fdd18dd0bdd00ca125c2069855?rik=SSSq2pnP6B1%2fwQ&pid=ImgRaw&r=0','2023-11-28','Gobierno de San Luis Río Colorado','Es una feria en la que viene muchos juegos mecánicos y la gente suele ir a divertirse y pasear un rato, además de disfrutar buena comida y cerveza','San Luis Río Colorado');
INSERT INTO `` (`id`,`title`,`description`,`image`,`date`,`author`,`text`,`location`) VALUES (12,'Beer Fest','Un evento dedicado 100% a las cervezas artesanales','https://th.bing.com/th/id/R.2d54cc9782aebe2025b3cc7510d41275?rik=qc9GPW%2bbJdYqmg&pid=ImgRaw&r=0','2023-06-24','Gobierno de San Luis Río COlorado','Es un evento en el cual se le da promoción a distintos negocios los cuales se dedican a la creación de cervezas artesanales, dando promoción a estos negocios. Además, se suele disfrutar de buena música a la par de tomar una buena cerveza','San Luis Río Colorado');
INSERT INTO `` (`id`,`title`,`description`,`image`,`date`,`author`,`text`,`location`) VALUES (13,'Obregoneada','La ciduadanía se reúne en la avenida principal del pueblo','https://i.ytimg.com/vi/BQXQ4SSDuWU/maxresdefault.jpg','2023-12-24','Ciudadanos','La gente de San Luis Río Colorado se reune en masa en la avenida principal del pueblo, celebrando algún acontecimiento importante para el país.','San Luis Río Colorado');
INSERT INTO `` (`id`,`title`,`description`,`image`,`date`,`author`,`text`,`location`) VALUES (14,'Clase de Yoga','Clases de yoga gratuitas para relajar el cuerpo y mente','https://th.bing.com/th/id/R.c0f7637618732394a3add2ff534f4de3?rik=SIRwCTnGR9JUKQ&riu=http%3a%2f%2fblissyogact.com%2fwp-content%2fgallery%2fdate-night-partner-yoga%2fDSC06273.jpg&ehk=I1sQ1Zv90q8Y9zLPq%2f38hJysYsePlzuxmbZ195mnyN0%3d&risl=&pid=ImgRaw&r=0','2023-11-11','Yoga Inc.','El realizar una buena práctica de yoga es de mucha ayuda para el estrés y ansiedad que acumulamos día a día','Mexicali');
INSERT INTO `` (`id`,`title`,`description`,`image`,`date`,`author`,`text`,`location`) VALUES (15,'Senderismo','Guía de senderismo en grupo por las montañas de la Rumorosa','https://th.bing.com/th/id/R.cc29aba4e4232aef33ec5a90fa20f01f?rik=WTbrw4tIifEF4w&pid=ImgRaw&r=0','2023-11-27','Senderismo Inc.','Realizar sendersimo es una de las prácticas más beneificosas para el metabolismo y el sistema circulatorio ya aue activa estos sistemas','Mexicali');
INSERT INTO `` (`id`,`title`,`description`,`image`,`date`,`author`,`text`,`location`) VALUES (16,'Baja 500','Viviendo la adrenalina de los deportes extremos ','https://utvsportsmag.com/wp-content/uploads/2021/06/2021_Baja_500_GetSOME_WM-020474-scaled.jpg','2024-01-01','Baja 500','La baja 500 se celebra hace muchos años reuniendo a gente apasioanda a los deportes extremos','Ensenada');
INSERT INTO `` (`id`,`title`,`description`,`image`,`date`,`author`,`text`,`location`) VALUES (17,'Carnaval Ensenada','Un carnaval para pasar el rato con toda la familia','https://th.bing.com/th/id/R.c16387cfea51cc0440613ed5c832919b?rik=ZkV%2b2L1HhBl%2f7w&pid=ImgRaw&r=0','2024-03-01','Gobierno de Ensenada','El carnaval de Enseanada es un evento en el cual se presentan distintas instituciones con sus camiones y realizan danzas para celebrar','Ensenada');
INSERT INTO `` (`id`,`title`,`description`,`image`,`date`,`author`,`text`,`location`) VALUES (18,'Charles Ans','El famoso artista y cantante Charles Ans nos deleita con sus mejores canciones','https://th.bing.com/th/id/R.ad08882285c1a2bdda597f071641443e?rik=ANHpywQ9KqjiGQ&pid=ImgRaw&r=0','2023-12-01','Gobierno de Tijuana','Escuchar al famoso cantante y artista Charles Ans es una oportunidad como ninguna otra','Tijuana');
